import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Typography, Container, Divider, Link } from "@mui/material";
export const PrivacyPolicy = () => {
    return (_jsxs(Container, { maxWidth: "md", sx: {
            background: (theme) => theme.palette.mode === "dark"
                ? "rgba(0, 0, 0, 0.2)"
                : "rgba(255, 255, 255, 0.7)",
            backdropFilter: "blur(10px)",
            boxShadow: "none",
            borderBottom: (theme) => `1px solid ${theme.palette.divider}`,
            py: 6,
        }, children: [_jsx(Typography, { variant: "h3", component: "h1", gutterBottom: true, align: "center", sx: { color: "#00ff88" }, children: "Politique de confidentialit\u00E9" }), _jsx(Divider, { sx: { my: 4, borderColor: "rgba(255, 255, 255, 0.2)" } }), _jsx(Typography, { variant: "h5", component: "h2", gutterBottom: true, sx: { color: "#00ff88" }, children: "1. Introduction" }), _jsxs(Typography, { variant: "body1", align: "center", sx: {
                    color: "text.secondary",
                    mb: 2,
                }, children: ["L\u2019association ", _jsx("strong", { children: "Danse Contemporaine" }), " (ci-apr\u00E8s \u00AB l\u2019Association \u00BB) s\u2019engage \u00E0 prot\u00E9ger la vie priv\u00E9e de ses membres, \u00E9l\u00E8ves et visiteurs. Cette politique de confidentialit\u00E9 explique comment nous collectons, utilisons et prot\u00E9geons vos donn\u00E9es personnelles conform\u00E9ment au", " ", _jsx(Link, { href: "https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX%3A32016R0679", target: "_blank", rel: "noopener noreferrer", sx: { color: "#00ff88" }, children: "R\u00E8glement G\u00E9n\u00E9ral sur la Protection des Donn\u00E9es (RGPD)" }), " ", "et \u00E0 la loi fran\u00E7aise."] }), _jsx(Divider, { sx: { my: 4, borderColor: "rgba(255, 255, 255, 0.2)" } }), _jsx(Typography, { variant: "h5", component: "h2", gutterBottom: true, sx: { color: "#00ff88" }, children: "2. Donn\u00E9es personnelles collect\u00E9es" }), _jsx(Typography, { variant: "body1", align: "center", sx: {
                    color: "text.secondary",
                    mb: 2,
                }, children: "Nous pouvons collecter les donn\u00E9es suivantes :" }), _jsxs(Typography, { component: "ul", sx: { pl: 4, mb: 2 }, children: [_jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Donn\u00E9es d\u2019identification" }), " : Nom, pr\u00E9nom, adresse e-mail, num\u00E9ro de t\u00E9l\u00E9phone (pour les inscriptions aux cours)."] }), _jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Donn\u00E9es de paiement" }), " : Informations bancaires (uniquement via des plateformes s\u00E9curis\u00E9es comme Stripe ou PayPal, nous ne stockons pas ces donn\u00E9es)."] }), _jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Donn\u00E9es de navigation" }), " : Adresse IP, cookies, pages visit\u00E9es (via Google Analytics, sous r\u00E9serve de votre consentement)."] }), _jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Donn\u00E9es sp\u00E9cifiques aux cours" }), " : Niveau de danse, pr\u00E9f\u00E9rences artistiques (pour personnaliser votre exp\u00E9rience)."] })] }), _jsx(Divider, { sx: { my: 4, borderColor: "rgba(255, 255, 255, 0.2)" } }), _jsx(Typography, { variant: "h5", component: "h2", gutterBottom: true, sx: { color: "#00ff88" }, children: "3. Finalit\u00E9s du traitement" }), _jsx(Typography, { variant: "body1", align: "center", sx: {
                    color: "text.secondary",
                    mb: 2,
                }, children: "Vos donn\u00E9es sont utilis\u00E9es pour :" }), _jsxs(Typography, { component: "ul", sx: { pl: 4, mb: 2 }, children: [_jsx(Typography, { component: "li", children: "G\u00E9rer votre inscription aux cours et ateliers." }), _jsx(Typography, { component: "li", children: "Vous envoyer des informations sur vos r\u00E9servations et les actualit\u00E9s de l\u2019association (si vous avez donn\u00E9 votre consentement)." }), _jsx(Typography, { component: "li", children: "Am\u00E9liorer notre site web et nos services (via des cookies analytiques)." }), _jsx(Typography, { component: "li", children: "Respecter nos obligations l\u00E9gales (comptabilit\u00E9, s\u00E9curit\u00E9, etc.)." })] }), _jsx(Divider, { sx: { my: 4, borderColor: "rgba(255, 255, 255, 0.2)" } }), _jsx(Typography, { variant: "h5", component: "h2", gutterBottom: true, sx: { color: "#00ff88" }, children: "4. Base l\u00E9gale du traitement" }), _jsx(Typography, { variant: "body1", align: "center", sx: {
                    color: "text.secondary",
                    mb: 2,
                }, children: "Nous traitons vos donn\u00E9es sur les bases l\u00E9gales suivantes :" }), _jsxs(Typography, { component: "ul", sx: { pl: 4, mb: 2 }, children: [_jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Ex\u00E9cution d\u2019un contrat" }), " : Pour g\u00E9rer votre inscription aux cours (article 6.1.b du RGPD)."] }), _jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Consentement" }), " : Pour les cookies et les newsletters (article 6.1.a du RGPD). Vous pouvez retirer votre consentement \u00E0 tout moment."] }), _jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Obligation l\u00E9gale" }), " : Pour r\u00E9pondre \u00E0 des obligations comptables ou administratives (article 6.1.c du RGPD)."] }), _jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Int\u00E9r\u00EAt l\u00E9gitime" }), " : Pour am\u00E9liorer nos services (article 6.1.f du RGPD), sous r\u00E9serve de vos droits."] })] }), _jsx(Divider, { sx: { my: 4, borderColor: "rgba(255, 255, 255, 0.2)" } }), _jsx(Typography, { variant: "h5", component: "h2", gutterBottom: true, sx: { color: "#00ff88" }, children: "5. Dur\u00E9e de conservation" }), _jsx(Typography, { variant: "body1", align: "center", sx: {
                    color: "text.secondary",
                    mb: 2,
                }, children: "Vos donn\u00E9es sont conserv\u00E9es pendant :" }), _jsxs(Typography, { component: "ul", sx: { pl: 4, mb: 2 }, children: [_jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "3 ans" }), " pour les donn\u00E9es d\u2019inscription (\u00E0 partir de votre derni\u00E8re activit\u00E9)."] }), _jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "13 mois" }), " pour les cookies (sauf retrait de votre consentement)."] }), _jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "10 ans" }), " pour les donn\u00E9es comptables (obligation l\u00E9gale)."] })] }), _jsx(Divider, { sx: { my: 4, borderColor: "rgba(255, 255, 255, 0.2)" } }), _jsx(Typography, { variant: "h5", component: "h2", gutterBottom: true, sx: { color: "#00ff88" }, children: "6. Vos droits" }), _jsx(Typography, { variant: "body1", align: "center", sx: {
                    color: "text.secondary",
                    mb: 2,
                }, children: "Conform\u00E9ment au RGPD, vous disposez des droits suivants :" }), _jsxs(Typography, { component: "ul", sx: { pl: 4, mb: 2 }, children: [_jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Droit d\u2019acc\u00E8s" }), " : Demander une copie de vos donn\u00E9es personnelles."] }), _jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Droit de rectification" }), " : Corriger des donn\u00E9es inexactes."] }), _jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Droit \u00E0 l\u2019effacement" }), " : Supprimer vos donn\u00E9es (sous r\u00E9serve des obligations l\u00E9gales)."] }), _jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Droit \u00E0 la limitation" }), " : Limiter le traitement de vos donn\u00E9es."] }), _jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Droit \u00E0 la portabilit\u00E9" }), " : R\u00E9cup\u00E9rer vos donn\u00E9es dans un format structur\u00E9."] }), _jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Droit d\u2019opposition" }), " : Vous opposer au traitement de vos donn\u00E9es pour des motifs l\u00E9gitimes."] })] }), _jsxs(Typography, { variant: "body1", align: "center", sx: {
                    color: "text.secondary",
                    mb: 2,
                }, children: ["Pour exercer ces droits, envoyez un e-mail \u00E0", " ", _jsx(Link, { href: "mailto:contact@danse-contemporaine.fr", sx: { color: "#00ff88" }, children: "contact@danse-contemporaine.fr" }), " ", "ou un courrier \u00E0 l\u2019adresse de l\u2019association. Nous r\u00E9pondrons dans un d\u00E9lai d\u2019", _jsx("strong", { children: "1 mois" }), "."] }), _jsx(Divider, { sx: { my: 4, borderColor: "rgba(255, 255, 255, 0.2)" } }), _jsx(Typography, { variant: "h5", component: "h2", gutterBottom: true, sx: { color: "#00ff88" }, children: "7. Utilisation des cookies" }), _jsx(Typography, { variant: "body1", align: "center", sx: {
                    color: "text.secondary",
                    mb: 2,
                }, children: "Notre site utilise des cookies pour :" }), _jsxs(Typography, { component: "ul", sx: { pl: 4, mb: 2 }, children: [_jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Cookies n\u00E9cessaires" }), " : Pour le bon fonctionnement du site (ex : session utilisateur). Ces cookies ne peuvent pas \u00EAtre d\u00E9sactiv\u00E9s."] }), _jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Cookies analytiques" }), " : Pour mesurer la fr\u00E9quentation du site (via Google Analytics). Ces cookies sont soumis \u00E0 votre consentement."] })] }), _jsx(Typography, { variant: "body1", align: "center", sx: {
                    color: "text.secondary",
                    mb: 2,
                }, children: "Vous pouvez g\u00E9rer vos pr\u00E9f\u00E9rences de cookies via la banni\u00E8re qui appara\u00EEt \u00E0 votre premi\u00E8re visite, ou en cliquant sur le lien \u00AB G\u00E9rer les cookies \u00BB en bas de page." }), _jsx(Divider, { sx: { my: 4, borderColor: "rgba(255, 255, 255, 0.2)" } }), _jsx(Typography, { variant: "h5", component: "h2", gutterBottom: true, sx: { color: "#00ff88" }, children: "8. S\u00E9curit\u00E9 des donn\u00E9es" }), _jsx(Typography, { variant: "body1", align: "center", sx: {
                    color: "text.secondary",
                    mb: 2,
                }, children: "Nous mettons en \u0153uvre des mesures techniques et organisationnelles pour prot\u00E9ger vos donn\u00E9es contre les acc\u00E8s non autoris\u00E9s, les pertes ou les destructions. Cependant, aucune transmission sur Internet n\u2019est totalement s\u00E9curis\u00E9e. Nous ne pouvons pas garantir une s\u00E9curit\u00E9 absolue." }), _jsx(Divider, { sx: { my: 4, borderColor: "rgba(255, 255, 255, 0.2)" } }), _jsx(Typography, { variant: "h5", component: "h2", gutterBottom: true, sx: { color: "#00ff88" }, children: "9. Modifications de cette politique" }), _jsx(Typography, { variant: "body1", align: "center", sx: {
                    color: "text.secondary",
                    mb: 2,
                }, children: "Nous nous r\u00E9servons le droit de modifier cette politique de confidentialit\u00E9 \u00E0 tout moment. Les modifications seront publi\u00E9es sur cette page et, si les changements sont significatifs, nous vous en informerons par e-mail ou via une notification sur le site." }), _jsx(Divider, { sx: { my: 4, borderColor: "rgba(255, 255, 255, 0.2)" } }), _jsx(Typography, { variant: "h5", component: "h2", gutterBottom: true, sx: { color: "#00ff88" }, children: "10. Contact" }), _jsx(Typography, { variant: "body1", align: "center", sx: {
                    color: "text.secondary",
                    mb: 2,
                }, children: "Pour toute question concernant cette politique de confidentialit\u00E9, contactez-nous :" }), _jsxs(Typography, { component: "ul", sx: { pl: 4, mb: 2 }, children: [_jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "E-mail" }), " :", " ", _jsx(Link, { href: "mailto:contact@danse-contemporaine.fr", sx: { color: "#00ff88" }, children: "contact@danse-contemporaine.fr" })] }), _jsxs(Typography, { component: "li", children: [_jsx("strong", { children: "Adresse postale" }), " : 12 Rue de la Danse, 75000 Paris"] })] }), _jsxs(Typography, { sx: {
                    color: "text.secondary",
                    mt: 4,
                    fontStyle: "italic",
                }, children: ["Derni\u00E8re mise \u00E0 jour : ", new Date().toLocaleDateString("fr-FR")] })] }));
};
